LangString addOrReinstall ${LANG_ROMANIAN} "Adaugă sau reinstalează componentele"
LangString alreadyInstalled ${LANG_ROMANIAN} "Aplicație deja instalată"
LangString alreadyInstalledLong ${LANG_ROMANIAN} "${PRODUCTNAME} ${VERSION} este deja instalată. Alege operația dorită și continuă."
LangString appRunning ${LANG_ROMANIAN} "{{product_name}} este deschisă. Închide aplicația și încearcă din nou."
LangString appRunningOkKill ${LANG_ROMANIAN} "{{product_name}} este deschisă.$\nApasă OK pentru a o închide."
LangString chooseMaintenanceOption ${LANG_ROMANIAN} "Alege operația de întreținere."
LangString choowHowToInstall ${LANG_ROMANIAN} "Alege modul de instalare pentru ${PRODUCTNAME}."
LangString createDesktop ${LANG_ROMANIAN} "Creează o scurtătură pe desktop"
LangString dontUninstall ${LANG_ROMANIAN} "Păstrează instalarea existentă"
LangString dontUninstallDowngrade ${LANG_ROMANIAN} "Păstrează instalarea existentă (revenirea la o versiune veche necesită dezinstalare)"
LangString failedToKillApp ${LANG_ROMANIAN} "Închiderea aplicației {{product_name}} a eșuat. Închide-o manual și încearcă din nou."
LangString installingWebview2 ${LANG_ROMANIAN} "Se instalează WebView2…"
LangString newerVersionInstalled ${LANG_ROMANIAN} "Există o versiune mai nouă de ${PRODUCTNAME}. Pentru instalarea acestei versiuni, dezinstalează mai întâi versiunea existentă."
LangString older ${LANG_ROMANIAN} "mai veche"
LangString olderOrUnknownVersionInstalled ${LANG_ROMANIAN} "Există o versiune $R4 de ${PRODUCTNAME}. Alege operația dorită pentru a continua."
LangString silentDowngrades ${LANG_ROMANIAN} "Revenirea la o versiune veche necesită instalatorul cu interfață grafică.$\n"
LangString unableToUninstall ${LANG_ROMANIAN} "Dezinstalarea nu a reușit."
LangString uninstallApp ${LANG_ROMANIAN} "Dezinstalează ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ROMANIAN} "Dezinstalează înainte de instalare"
LangString unknown ${LANG_ROMANIAN} "necunoscută"
LangString webview2AbortError ${LANG_ROMANIAN} "WebView2 nu a putut fi instalat. Aplicația are nevoie de acesta. Repornește instalatorul."
LangString webview2DownloadError ${LANG_ROMANIAN} "Descărcarea WebView2 a eșuat: $0"
LangString webview2DownloadSuccess ${LANG_ROMANIAN} "Programul de instalare WebView2 a fost descărcat."
LangString webview2Downloading ${LANG_ROMANIAN} "Se descarcă programul de instalare WebView2…"
LangString webview2InstallError ${LANG_ROMANIAN} "Instalarea WebView2 a eșuat. Cod: $1"
LangString webview2InstallSuccess ${LANG_ROMANIAN} "WebView2 a fost instalat."
LangString deleteAppData ${LANG_ROMANIAN} "Șterge datele aplicației"
